appprincipal/curso/urls.py
from . import views
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.urls import path


from appprincipal.curso.views import *

app_name = 'curso'

urlpatterns = [
    path('curso_cadast/', Cadast_CursoCreateView.as_view(), name="curso_cadast"),
    #path('tipoprod/produto/', Cadast_ProdCreateView.as_view(), name = 'produto'),
    #path('produto/', ListaProdutoListView.as_view(), name = 'lista_produto'),
    path('curso/', views.CursoListView, name = "lista_curso"),
    path('curso/<pk>', CursoUpdateView.as_view(), name = 'update_curso'),
    path('curso/excluir/<pk>', CursoDeleteView.as_view(), name = 'deleta_curso'),
    path('cursoacesso/', CursoTemplateView.as_view(), name = "curso_acesso"),

]

appprincipal/instituicao/urls.py
from . import views
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.urls import path


from appprincipal.instituicao.views import *

app_name = 'instituicao'

urlpatterns = [
    # path('cria_instituicao/', InstituicaoCreateView.as_view(), name="cria_instituicao"),
    # path('cria_dirigente/', DirigenteCreateView.as_view(), name="cria_dirigente"),
    path('institucional/', InstituicaoTemplateView.as_view(), name = "institucional"),
    path('cria_instpar/', Cadast_InstParCreateView.as_view(), name="cria_instpar"),
    path('cria_instval/', Cadast_InstValCreateView.as_view(), name="cria_instval"),
    
    path('update_instpar/<pk>', Update_InstParUpdateView.as_view(), name="update_instpar"),
    path('update_instval/<pk>', Update_InstValUpdateView.as_view(), name="update_instval"),

    path('cria_dirigentepar/', Cadast_DirigenteParCreateView.as_view(), name="cria_dirigentepar"),
    path('cria_dirigenteval/', Cadast_DirigenteValCreateView.as_view(), name="cria_dirigenteval"),
    
    
    path('cria_diretor/', Cadast_DiretorParCreateView.as_view(), name="cria_diretor"),
    path('cria_superval/', Cadast_SuperValCreateView.as_view(), name="cria_super"),

    path('cria_func/', Cadast_FuncionarioCreateView.as_view(), name="cria_func"),

    path('instpar/', views.InstParListView, name = "lista_instpar"),
    path('instval/', views.InstValListView, name = "lista_instval"),

    
]

appprincipal/registration/urls.py
from . import views
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.urls import path
#from django.contrib.auth import views 
from appprincipal.registration.views import *


app_name = 'registration'



urlpatterns = [
    

    path('logout/', views.logoutUser, name = "logout"),
    path('login/', views.loginPage, name = "login"),
    path('register/', views.registerPage, name = "register"),
    path('registrar/', RegistrationTemplateView.as_view(), name = "registrar"),
    path('cria_users/', UsuariosCriarTemplateView.as_view(), name = "cria_users"),
    path('cria_userssuper/', UsuariosCriarSuperTemplateView.as_view(), name = "cria_userssuper"),
    path('usuarios/', views.UsersListView, name = "usuarios"),
    path('deletar/<pk>', UsuarioDeleteView.as_view(), name = "deletar"),
    path('profile/', views.profileUpdate, name='profile'),
    path('usuarios/<pk>', UsersUpdateView.as_view(), name = 'update_users'),
    path('tipo_user/', Cadast_TipoUsersCreateView.as_view(), name = 'tipo_user'),
    path('cadast_user/', Cadast_UserCreateView.as_view(), name = "cadast_user"),
    # path('reset_senha/', views.PassowordResetView, name = 'reset_senha'),
    # path('reset_senha/done', views.PassowordResetDoneView, name = 'reset_senha_done'),
    # path('reset/<uidb64>/token/', views.PassowordResetConfirmView, name = 'reset_senha_confirm'),
    # path('reset/done', views.PassowordResetCompleteView, name = 'reset_senha_confirm'),
    


]

appprincipal/urls.py
#from core.views import LocaisList, IndexTemplateView, LocalDetailView, RegCreateView, Pt1CreateView
from . import views
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.urls import path
from appprincipal.views import *
from . import views

app_name = 'appprincipal'

urlpatterns = [
    
    path('', IndexTemplateView.as_view(), name = 'index'),
]

projinst/urls.py
import appprincipal
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appprincipal.urls', namespace='appprincipal')),
    
    path('regis/', include('appprincipal.registration.urls')), 
    path('curso/', include('appprincipal.curso.urls')),
    path('insti/', include('appprincipal.instituicao.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_confirm.html'), name='reset_password'),#1
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='reset_password'),#1
    #path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    #path('password_reset/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_don'),#2
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name='password_reset_done'),#2
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),#3
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),#3
    #path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html', name='password_reset_complete'),name='password_reset_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    #path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_complete"),
    
    # # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
    #     name='password_change_done'),
         
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    #  name='password_reset_complete'),

    
    
]

appprincipal/curso/forms.py
from appprincipal.curso.models import *
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrarTipoCursoForm(forms.ModelForm):

    class Meta:
        model = Curso
        fields='__all__'

appprincipal/instituicao/forms.py
from appprincipal.instituicao.models import *
from appprincipal.registration.models import *
from django import forms
from django.forms import ModelForm

class RegistrarInst_ParForm(forms.ModelForm):

    class Meta:
        model = Inst_Par
        fields='__all__'

class RegistrarInst_ValForm(forms.ModelForm):

    class Meta:
        model = Inst_Val
        fields='__all__'

class RegistrarDirigenteParForm(forms.ModelForm):

    class Meta:
        model = DirigentePar
        fields='__all__'

class RegistrarDirigenteValForm(forms.ModelForm):

    class Meta:
        model = DirigenteVal
        fields='__all__'

class RegistrarDiretorParForm(forms.ModelForm):

    class Meta:
        model = DiretorPar
        fields='__all__'

class RegistrarSuperValForm(forms.ModelForm):

    class Meta:
        model = SuperVal
        fields='__all__'

class RegistrarUsuarioForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields='__all__'

# class RegistrarInst_ParForm(forms.ModelForm):

#     class Meta:
#         model = Inst_Parc
#         fields='__all__'




# class RegistrarDirigenteForm(forms.ModelForm):

#     class Meta:
#         model = Dirigente
#         fields='__all__'



# class RegistrarUniversidadeForm(forms.ModelForm):

#     class Meta:
#         model = Instituicao
#         fields='__all__'

appprincipal/curso/views.py
from django.shortcuts import render
from appprincipal.curso.forms import *
from appprincipal.registration.decorators import unauthenticated_user, allowed_users, admin_only
from django.shortcuts import render
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
# Create your views here.
from django.db import models
from ckeditor.fields import RichTextField
import datetime
from django.contrib.auth.decorators import login_required #para Functions Based Views
from django.contrib import messages
from django.urls import reverse_lazy,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin #para Classes Based Views
from django.contrib.auth.models import Group
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
import requests
from appprincipal.curso.models import *
# Create your views here.

class CursoTemplateView(TemplateView):
    template_name = "curso/cursoacesso.html"
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['funcionario', 'coord', 'super', 'dirigente', 'diretor', 'admin']))
    def get (self, request):
        return render(request, self.template_name)

class Cadast_CursoCreateView(CreateView):
    #funcionario
    template_name = "curso/cadast_curso.html"
    model = Curso
    form_class = RegistrarTipoCursoForm
    success_url = reverse_lazy("curso:lista_curso")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['funcionario', 'super', 'diretor', 'admin']))
    def get (self, request):

        return render(request, self.template_name)

@login_required
def CursoListView(ListView):
    #funcionario
    cursos = Curso.objects.all()
    
    contexto = {
        'cursos': cursos
    }
    
    return render(ListView, "curso/cursos.html",contexto)


class CursoUpdateView(LoginRequiredMixin, UpdateView):
    #funcionario
    template_name = "curso/atualiza_curso.html"
    model = Curso
    fields = '__all__'
    context_object_name = "curso"
    success_url = reverse_lazy("curso:lista_curso")
   #@method_decorator(allowed_users(allowed_roles=['funcionario', 'super', 'diretor', 'admin']))    
    # def get (self, request, pk):

    #     return render(request, self.template_name)

class CursoDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "curso/exclui_curso.html"
    model = Curso
    context_object_name =  'curso'
    #@method_decorator(login_required)
    #@method_decorator(allowed_users(allowed_roles=['funcionario', 'super', 'diretor', ]))
    def get_success_url (self):

        return reverse("curso:lista_curso")

appprincipal/instituicao/views.py
from appprincipal.instituicao.forms import *
from appprincipal.instituicao.models import *
from appprincipal.registration.models import *
from appprincipal.registration.decorators import unauthenticated_user, allowed_users, admin_only
from django.shortcuts import render
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
# Create your views here.
from django.db import models
from ckeditor.fields import RichTextField
import datetime
from django.contrib.auth.decorators import login_required #para Functions Based Views
from django.contrib import messages
from django.urls import reverse_lazy,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin #para Classes Based Views
from django.contrib.auth.models import Group
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
import requests


class InstituicaoTemplateView(TemplateView):
    template_name = "instituicao/instacesso.html"
    @method_decorator(allowed_users(allowed_roles=['admin', 'coord', 'super', 'dirigente', 'diretor']))
    @method_decorator(login_required)
    def get (self, request):
        return render(request, self.template_name)


class Cadast_InstParCreateView(CreateView):
    template_name = "instituicao/cadast_instpar.html"
    model = Inst_Par
    fields = '__all__'
    success_url = reverse_lazy("instituicao:lista_instpar")
    @method_decorator(allowed_users(allowed_roles=['admin', 'dirigente', 'diretor']))
    @method_decorator(login_required)
    def get (self, request):

        return render(request, self.template_name)


class Update_InstParUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "instituicao/update_instpar.html"
    model = Inst_Par
    fields = '__all__'
    #fields = ['nome_instituicao']
    context_object_name = "inst_par"
    success_url = reverse_lazy("instituicao:lista_instpar")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    #@method_decorator(login_required)
    # def get (self, request, pk):

    #     return render(request, self.template_name)

class Cadast_InstValCreateView(CreateView):
    template_name = "instituicao/cadast_instval.html"
    model = Inst_Val
    form_class = RegistrarInst_ValForm
    success_url = reverse_lazy("instituicao:lista_instval")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'super']))
    def get (self, request):
        return render(request, self.template_name)

class Update_InstValUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "instituicao/update_instval.html"
    model = Inst_Val
    fields = '__all__'
    #fields = ['nome_instituicao']
    context_object_name = "inst_val"
    success_url = reverse_lazy("instituicao:lista_instval")


class Cadast_FuncionarioCreateView(CreateView):
    template_name = "instituicao/cadast_func.html"
    model = Usuario
    form_class = RegistrarUsuarioForm
    success_url = reverse_lazy("regis:usuarios")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'super']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_DirigenteParCreateView(CreateView):
    template_name = "instituicao/cadast_dirigentepar.html"
    model = DirigentePar
    form_class = RegistrarDirigenteParForm
    success_url = reverse_lazy("appprincipal:index")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin','diretor']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_DirigenteValCreateView(CreateView):
    template_name = "instituicao/cadast_dirigenteval.html"
    model = DirigenteVal
    form_class = RegistrarDirigenteValForm
    success_url = reverse_lazy("appprincipal:index")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin','super']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_DiretorParCreateView(CreateView):
    template_name = "instituicao/cadast_diretorpar.html"
    model = DiretorPar
    form_class = RegistrarDiretorParForm
    success_url = reverse_lazy("appprincipal:index")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'diretor']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_SuperValCreateView(CreateView):
    template_name = "instituicao/cadast_superval.html"
    model = SuperVal
    form_class = RegistrarSuperValForm
    success_url = reverse_lazy("appprincipal:index")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'super']))
    def get (self, request):

        return render(request, self.template_name)

@login_required
def InstParListView(ListView):
    #funcionario
    instpar = Inst_Par.objects.all()
    
    contexto = {
        'instpar': instpar
    }
    
    return render(ListView, "instituicao/instpar.html",contexto)

@login_required
def InstValListView(ListView):
    #funcionario
    instval = Inst_Val.objects.all()
    
    contexto = {
        'instval': instval
    }
    
    return render(ListView, "instituicao/instval.html",contexto)

appprincipal/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
import requests
from appprincipal.registration.decorators import unauthenticated_user, allowed_users, admin_only
import json
import datetime
# Create your views here.
from django.views import generic
import requests
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin #para Classes Based Views
from django.contrib.auth.decorators import login_required #para Functions Based Views

class IndexTemplateView(TemplateView):
    template_name = "index.html"
    @method_decorator(login_required, allowed_users(allowed_roles=['customer']))
    def get (self, request):
        return render(request, self.template_name)

appprincipal/templates/instituicao/cadast_dirigentepar.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

{% load widget_tweaks %}
{% block conteudo %}
<div class="container mt-5">
    <h2>Cadastrar Dirigente Instituição Parceira</h2>
    </br>
<div class="container mt-3">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Nome do Usuario</label></br>
            {% render_field form.user %}
        </div>
        <div class="form-group">
            <label>Nome da Instituicao Parceira</label></br>
            {% render_field form.instituicao %}
        </div>
        <div class="form-group">
            <label>Nome do dirigente institucional da parceira</label></br>
            {% render_field form.nome %}
        </div>
        <div class="form-group">
            <label>Sobrenome</label></br>
            {% render_field form.sobrenome %}
        </div>
        <div class="form-group">
            <label>cpf</label></br>
            {% render_field form.cpf %}
        </div>
        <div class="form-group">
            <label>Telefone</label></br>
            {% render_field form.tel %}
        </div>
        <div class="form-group">
            <label>Email</label></br>
            {% render_field form.email %}
        </div>
        
        <button type="submit">Cadastrar Dirigente da Inst Parceira</button></br></br>
        <a href="{% url 'instituicao:cria_instpar' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Próximo</a>
    </form>
</div>


{% endblock %}

appprincipal/templates/instituicao/cadast_instpar.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

{% load widget_tweaks %}
{% block conteudo %}
<div class="container mt-5">
    <h2>Cadastrar Instituição Parceira</h2>
    </br>
<div class="container mt-3">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Nome Instituicao Parceira</label></br>
            {% render_field form.nome_instituicao %}
        </div>
        <div class="form-group">
            <label>Endereço</label></br>
            {% render_field form.endereco %}
        </div>
        <div class="form-group">
            <label>Cidade</label></br>
            {% render_field form.cidade %}
        </div>
        <div class="form-group">
            <label>Estado</label></br>
            {% render_field form.estado %}
        </div>
        <div class="form-group">
            <label>Credenciamento</label></br>
            {% render_field form.credenciamento %}
        </div>
        <div class="form-group">
            <label>Mantenedora</label></br>
            {% render_field form.mantenedora %}
        </div>
        <div class="form-group">
            <label>Descrição</label></br>
            {% render_field form.descricao %}
        </div>
            <div class="form-group">
                <label>Dirigente</label></br>
                {% render_field form.dirigente %}
            </div>
    
        <button type="submit">Cadastrar Instituicao Parceira</button></br></br>
        <a href="{% url 'instituicao:cria_diretor' %}" class="btn btn-primary btn-lg active" role="button"
            aria-pressed="true">Próximo</a>

    </form>
</div>


{% endblock %}

appprincipal/templates/instituicao/cadast_superval.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

{% load widget_tweaks %}
{% block conteudo %}



<div class="container mt-3">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Nome do Usuario Superintendente Validadora</label></br>
            {% render_field form.user %}
        </div>
        <div class="form-group">
            <label>Nome da Instituicao Validadora</label></br>
            {% render_field form.instituicao %}
        </div>
        <div class="form-group">
            <label>Nome do Superitendente Institucional Validadora</label></br>
            {% render_field form.nome %}
        </div>

        <div class="form-group">
            <label>Sobrenome</label></br>
            {% render_field form.sobrenome %}
        </div>
        <div class="form-group">
            <label>cpf</label></br>
            {% render_field form.cpf %}
        </div>
        <div class="form-group">
            <label>Telefone</label></br>
            {% render_field form.tel %}
        </div>
        <div class="form-group">
            <label>Email</label></br>
            {% render_field form.email %}
        </div></br>

        <button type="submit">Cadastrar Superintendente da Inst Validadora</button></br></br>
<a href="{% url 'instituicao:cria_instval' %}" class="btn btn-primary btn-lg active" role="button"
    aria-pressed="true">Próximo</a>
    </form>
</div>


{% endblock %}

appprincipal/templates/instituicao/instacesso.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}


<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}


<div class="container mt-5">
<h2><a href="#">Institucional</a></h2>
</br>
    <p class="mb-3">Funções </p>
    <a href="{% url 'instituicao:cria_instpar' %}" class="btn btn-primary btn-lg active" role="button"
      aria-pressed="true">Criar Nova Instituicao Parceira</a></br></br>
    <a href="{% url 'instituicao:lista_instpar' %}" class="btn btn-primary btn-lg active" role="button"
      aria-pressed="true">Lista Instituicões Parceiras</a></br></br>
    <a href="{% url 'instituicao:cria_instval' %}" class="btn btn-primary btn-lg active" role="button"
      aria-pressed="true">Criar Nova Instituicao Validadora</a></br></br>
    <a href="{% url 'instituicao:lista_instval' %}" class="btn btn-primary btn-lg active" role="button"
      aria-pressed="true">Lista Instituicões Validadoras</a></br></br>
     
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Primeiro Acesso
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tipo desejado</h5></br></br>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Escolha a instituição a qual deseja ingressar:
      </div>
      <div class="modal-footer">
        <td><a href="{% url 'instituicao:cria_dirigentepar'  %}" class="btn btn-secondary">Instituição Parceira</a></td>
        <td><a href="{% url 'instituicao:cria_super'  %}" class="btn btn-primary">Instituição Validadora</a></td>
      </div>
    </div>
  </div>
</div>

{% endblock %}

appprincipal/templates/instituicao/instpar.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

<!-- Bloco de conteúdo da nossa página -->

{% block conteudo %}
<a href="{% url 'registration:cria_users' %}" class="btn btn-primary btn-lg active" role="button"
    aria-pressed="true">Próximo</a>
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Lista Instituicões Parceiras:</h5>

            <p class="card-text">

            </p>

            <form method="post">

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nome Instituicao Parceira</th>
                            
                            <th></th>
                        </tr>
                    </thead>


                    <tbody> {% for instpar in instpar %} <tr>
                            <td>{{ instpar.nome_instituicao }}</td>

                        <td><a href="{% url 'instituicao:update_instpar' instpar.id %}" class="btn btn-primary">Atualizar</a></td>
                        </tr> {% endfor %}

                    </tbody>
                    <td><a href="{% url 'instituicao:cria_instpar' %}" class="btn btn-outline-info">Criar Instituição Parceira</a></td> </br></br>
                    

            </form>
            </table>
        </div>
    </div>
</div>
{% endblock %}

appprincipal/templates/instituicao/instval.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

<!-- Bloco de conteúdo da nossa página -->

{% block conteudo %}
<div class="container mt-5">
   

            <form method="post">

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nome Instituicao Validadora</th>
                            
                            <th></th>
                        </tr>
                    </thead>


                    <tbody> {% for instval in instval %} <tr>
                            <td>{{ instval.nome_instituicao }}</td>
                                                    <td><a href="{% url 'instituicao:update_instval' instval.id %}" class="btn btn-primary">Atualizar</a></td>
                                                    
                        </tr> {% endfor %}
                    </tbody>


            </form>
            </table>
        </div>
    </div>
</div>
{% endblock %}

appprincipal/templates/instituicao/update_instval.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

{% load widget_tweaks %}

<!-- Bloco de conteúdo da nossa página -->

{% block conteudo %}
<a href="{% url 'registration:cria_userssuper' %}" class="btn btn-primary btn-lg active" role="button"
    aria-pressed="true">Próximo</a>
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Atualizar Dados da Inst validadora</h5>
                    <form method="post">
                        {% csrf_token %}
                        <!-- Nome Curso -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome da Instituição</span>
                            </div> {% render_field form.nome_instituicao class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Endereco</span>
                            </div>
                            {% render_field form.endereco class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Cidade</span>
                            </div>
                            {% render_field form.cidade class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Estado</span>
                            </div>
                            {% render_field form.estado class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Credenciamento</span>
                            </div>
                            {% render_field form.credenciamento class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Mantenedora</span>
                            </div>
                            {% render_field form.mantenedora class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Descrição</span>
                            </div>
                            {% render_field form.descricao class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Superintendente</span>
                            </div>
                            {% render_field form.superitende class+="form-control" %}
                        </div>
                       
                        <div class="text-right">
                            <a href="{% url 'appprincipal:index' %}" class="btn btn-outline-primary">Voltar</a>
                            <button type="submit" class="btn btn-primary">Atualiza</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}