appprincipal/curso/urls.py
from . import views
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.urls import path


from appprincipal.curso.views import *

app_name = 'curso'

urlpatterns = [
    path('curso_cadast/', Cadast_CursoCreateView.as_view(), name="curso_cadast"),
    #path('tipoprod/produto/', Cadast_ProdCreateView.as_view(), name = 'produto'),
    #path('produto/', ListaProdutoListView.as_view(), name = 'lista_produto'),
    path('curso/', views.CursoListView, name = "lista_curso"),
    path('curso/<pk>', CursoUpdateView.as_view(), name = 'update_curso'),
    path('curso/excluir/<pk>', CursoDeleteView.as_view(), name = 'deleta_curso'),
    path('cursoacesso/', CursoTemplateView.as_view(), name = "curso_acesso"),

]

appprincipal/instituicao/urls.py
from . import views
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.urls import path


from appprincipal.instituicao.views import *

app_name = 'instituicao'

urlpatterns = [
    # path('cria_instituicao/', InstituicaoCreateView.as_view(), name="cria_instituicao"),
    # path('cria_dirigente/', DirigenteCreateView.as_view(), name="cria_dirigente"),
    path('institucional/', InstituicaoTemplateView.as_view(), name = "institucional"),
    path('cria_instpar/', Cadast_InstParCreateView.as_view(), name="cria_instpar"),
    path('cria_instval/', Cadast_InstValCreateView.as_view(), name="cria_instval"),
    
    path('update_instpar/<pk>', Update_InstParUpdateView.as_view(), name="update_instpar"),
    path('update_instval/<pk>', Update_InstValUpdateView.as_view(), name="update_instval"),

    path('cria_dirigentepar/', Cadast_DirigenteParCreateView.as_view(), name="cria_dirigentepar"),
    path('cria_dirigenteval/', Cadast_DirigenteValCreateView.as_view(), name="cria_dirigenteval"),
    
    
    path('cria_diretor/', Cadast_DiretorParCreateView.as_view(), name="cria_diretor"),
    path('cria_superval/', Cadast_SuperValCreateView.as_view(), name="cria_super"),

    path('cria_func/', Cadast_FuncionarioCreateView.as_view(), name="cria_func"),

    path('instpar/', views.InstParListView, name = "lista_instpar"),
    path('instval/', views.InstValListView, name = "lista_instval"),

    
]

appprincipal/urls.py
#from core.views import LocaisList, IndexTemplateView, LocalDetailView, RegCreateView, Pt1CreateView
from . import views
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.urls import path
from appprincipal.views import *
from . import views

app_name = 'appprincipal'

urlpatterns = [
    
    path('', IndexTemplateView.as_view(), name = 'index'),
]

projinst/urls.py
import appprincipal
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appprincipal.urls', namespace='appprincipal')),
    
    path('regis/', include('appprincipal.registration.urls')), 
    path('curso/', include('appprincipal.curso.urls')),
    path('insti/', include('appprincipal.instituicao.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_confirm.html'), name='reset_password'),#1
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='reset_password'),#1
    #path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    #path('password_reset/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_don'),#2
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name='password_reset_done'),#2
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),#3
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),#3
    #path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html', name='password_reset_complete'),name='password_reset_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    #path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_complete"),
    
    # # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
    #     name='password_change_done'),
         
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    #  name='password_reset_complete'),

    
    
]

appprincipal/curso/models.py
from django.db import models
import datetime
from django.utils import timezone
from ckeditor.fields import RichTextField
# Create your models here.
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from appprincipal.registration.models import *
from appprincipal.instituicao.models import *


class Curso(models.Model):

    nome_inst = models.ForeignKey(Inst_Par, on_delete = models.CASCADE )
    
    nome_curso = models.CharField(max_length=50, null=False, blank=False)
    
    grau_curso = models.DecimalField(null=True, max_digits=12, decimal_places=2, blank=True)
    cod_emec = models.TextField(max_length=10, null=False, blank=False)    
        
    data_autorizacao = models.DateTimeField(auto_now_add= False, null=True)
    data_reconhecimento = models.DateTimeField(auto_now_add= False, null=True)
    data_renovacao = models.DateTimeField(auto_now_add= False, null=True)

    observacao = models.CharField(max_length=200, null=True)
    

    def __str__(self):
        return self.nome_curso

appprincipal/models.py
from django.db import models

# Create your models here.

appprincipal/curso/forms.py
from appprincipal.curso.models import *
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrarTipoCursoForm(forms.ModelForm):

    class Meta:
        model = Curso
        fields='__all__'

appprincipal/instituicao/forms.py
from appprincipal.instituicao.models import *
from appprincipal.registration.models import *
from django import forms
from django.forms import ModelForm

class RegistrarInst_ParForm(forms.ModelForm):

    class Meta:
        model = Inst_Par
        fields='__all__'

class RegistrarInst_ValForm(forms.ModelForm):

    class Meta:
        model = Inst_Val
        fields='__all__'

class RegistrarDirigenteParForm(forms.ModelForm):

    class Meta:
        model = DirigentePar
        fields='__all__'

class RegistrarDirigenteValForm(forms.ModelForm):

    class Meta:
        model = DirigenteVal
        fields='__all__'

class RegistrarDiretorParForm(forms.ModelForm):

    class Meta:
        model = DiretorPar
        fields='__all__'

class RegistrarSuperValForm(forms.ModelForm):

    class Meta:
        model = SuperVal
        fields='__all__'

class RegistrarUsuarioForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields='__all__'

# class RegistrarInst_ParForm(forms.ModelForm):

#     class Meta:
#         model = Inst_Parc
#         fields='__all__'




# class RegistrarDirigenteForm(forms.ModelForm):

#     class Meta:
#         model = Dirigente
#         fields='__all__'



# class RegistrarUniversidadeForm(forms.ModelForm):

#     class Meta:
#         model = Instituicao
#         fields='__all__'

appprincipal/curso/views.py
from django.shortcuts import render
from appprincipal.curso.forms import *
from appprincipal.registration.decorators import unauthenticated_user, allowed_users, admin_only
from django.shortcuts import render
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
# Create your views here.
from django.db import models
from ckeditor.fields import RichTextField
import datetime
from django.contrib.auth.decorators import login_required #para Functions Based Views
from django.contrib import messages
from django.urls import reverse_lazy,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin #para Classes Based Views
from django.contrib.auth.models import Group
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
import requests
from appprincipal.curso.models import *
# Create your views here.

class CursoTemplateView(TemplateView):
    template_name = "curso/cursoacesso.html"
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['funcionario', 'coord', 'super', 'dirigente', 'diretor', 'admin']))
    def get (self, request):
        return render(request, self.template_name)

class Cadast_CursoCreateView(CreateView):
    #funcionario
    template_name = "curso/cadast_curso.html"
    model = Curso
    form_class = RegistrarTipoCursoForm
    success_url = reverse_lazy("curso:lista_curso")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['funcionario', 'super', 'diretor', 'admin']))
    def get (self, request):

        return render(request, self.template_name)

@login_required
def CursoListView(ListView):
    #funcionario
    cursos = Curso.objects.all()
    
    contexto = {
        'cursos': cursos
    }
    
    return render(ListView, "curso/cursos.html",contexto)


class CursoUpdateView(LoginRequiredMixin, UpdateView):
    #funcionario
    template_name = "curso/atualiza_curso.html"
    model = Curso
    fields = '__all__'
    context_object_name = "curso"
    success_url = reverse_lazy("curso:lista_curso")
   #@method_decorator(allowed_users(allowed_roles=['funcionario', 'super', 'diretor', 'admin']))    
    # def get (self, request, pk):

    #     return render(request, self.template_name)

class CursoDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "curso/exclui_curso.html"
    model = Curso
    context_object_name =  'curso'
    #@method_decorator(login_required)
    #@method_decorator(allowed_users(allowed_roles=['funcionario', 'super', 'diretor', ]))
    def get_success_url (self):

        return reverse("curso:lista_curso")

appprincipal/instituicao/views.py
from appprincipal.instituicao.forms import *
from appprincipal.instituicao.models import *
from appprincipal.registration.models import *
from appprincipal.registration.decorators import unauthenticated_user, allowed_users, admin_only
from django.shortcuts import render
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
# Create your views here.
from django.db import models
from ckeditor.fields import RichTextField
import datetime
from django.contrib.auth.decorators import login_required #para Functions Based Views
from django.contrib import messages
from django.urls import reverse_lazy,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin #para Classes Based Views
from django.contrib.auth.models import Group
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
import requests


class InstituicaoTemplateView(TemplateView):
    template_name = "instituicao/instacesso.html"
    @method_decorator(allowed_users(allowed_roles=['admin', 'coord', 'super', 'dirigente', 'diretor']))
    @method_decorator(login_required)
    def get (self, request):
        return render(request, self.template_name)


class Cadast_InstParCreateView(CreateView):
    template_name = "instituicao/cadast_instpar.html"
    model = Inst_Par
    fields = '__all__'
    success_url = reverse_lazy("instituicao:lista_instpar")
    @method_decorator(allowed_users(allowed_roles=['admin', 'dirigente', 'diretor']))
    @method_decorator(login_required)
    def get (self, request):

        return render(request, self.template_name)


class Update_InstParUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "instituicao/update_instpar.html"
    model = Inst_Par
    fields = '__all__'
    #fields = ['nome_instituicao']
    context_object_name = "inst_par"
    success_url = reverse_lazy("instituicao:lista_instpar")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    #@method_decorator(login_required)
    # def get (self, request, pk):

    #     return render(request, self.template_name)

class Cadast_InstValCreateView(CreateView):
    template_name = "instituicao/cadast_instval.html"
    model = Inst_Val
    form_class = RegistrarInst_ValForm
    success_url = reverse_lazy("instituicao:lista_instval")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'super']))
    def get (self, request):
        return render(request, self.template_name)

class Update_InstValUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "instituicao/update_instval.html"
    model = Inst_Val
    fields = '__all__'
    #fields = ['nome_instituicao']
    context_object_name = "inst_val"
    success_url = reverse_lazy("instituicao:lista_instval")


class Cadast_FuncionarioCreateView(CreateView):
    template_name = "instituicao/cadast_func.html"
    model = Usuario
    form_class = RegistrarUsuarioForm
    success_url = reverse_lazy("regis:usuarios")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'super']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_DirigenteParCreateView(CreateView):
    template_name = "instituicao/cadast_dirigentepar.html"
    model = DirigentePar
    form_class = RegistrarDirigenteParForm
    success_url = reverse_lazy("appprincipal:index")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin','diretor']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_DirigenteValCreateView(CreateView):
    template_name = "instituicao/cadast_dirigenteval.html"
    model = DirigenteVal
    form_class = RegistrarDirigenteValForm
    success_url = reverse_lazy("appprincipal:index")
    #@method_decorator(allowed_users(allowed_roles=['admin']))
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin','super']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_DiretorParCreateView(CreateView):
    template_name = "instituicao/cadast_diretorpar.html"
    model = DiretorPar
    form_class = RegistrarDiretorParForm
    success_url = reverse_lazy("appprincipal:index")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'diretor']))
    def get (self, request):

        return render(request, self.template_name)

class Cadast_SuperValCreateView(CreateView):
    template_name = "instituicao/cadast_superval.html"
    model = SuperVal
    form_class = RegistrarSuperValForm
    success_url = reverse_lazy("appprincipal:index")
    @method_decorator(login_required)
    @method_decorator(allowed_users(allowed_roles=['admin', 'super']))
    def get (self, request):

        return render(request, self.template_name)

@login_required
def InstParListView(ListView):
    #funcionario
    instpar = Inst_Par.objects.all()
    
    contexto = {
        'instpar': instpar
    }
    
    return render(ListView, "instituicao/instpar.html",contexto)

@login_required
def InstValListView(ListView):
    #funcionario
    instval = Inst_Val.objects.all()
    
    contexto = {
        'instval': instval
    }
    
    return render(ListView, "instituicao/instval.html",contexto)

appprincipal/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DeleteView
import requests
from appprincipal.registration.decorators import unauthenticated_user, allowed_users, admin_only
import json
import datetime
# Create your views here.
from django.views import generic
import requests
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin #para Classes Based Views
from django.contrib.auth.decorators import login_required #para Functions Based Views

class IndexTemplateView(TemplateView):
    template_name = "index.html"
    @method_decorator(login_required, allowed_users(allowed_roles=['customer']))
    def get (self, request):
        return render(request, self.template_name)

appprincipal/templates/curso/atualiza_curso.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

{% load widget_tweaks %}

<!-- Bloco de conteúdo da nossa página -->

{% block conteudo %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Atualizar Dados de Curso</h5>
                    <form method="post">
                        {% csrf_token %}
                        <!-- Nome Curso -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome do Curso</span>
                            </div> {% render_field form.nome_curso class+="form-control" %}
                        </div>

                        <!-- Preço -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Grau Curso/span>
                            </div>
                            {% render_field form.nome_inst class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Grau Curso/span>
                            </div>
                            {% render_field form.grau_curso class+="form-control" %}
                        </div>  
                                    <!-- Nome tipo-->
                        
                        <div class="input-group mb-3">
                         <div class="input-group-prepend">
                            <span class="input-group-text">Cód e-MEC</span>
                        </div>
                            {% render_field form.cod_emec class+="form-control" %}
                        </div>     
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Data Autorização</span>
                            </div>
                            {% render_field form.data_autorizacao class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Data Reconhecimento</span>
                            </div>
                            {% render_field form.data_reconhecimento class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Data Renovação</span>
                            </div>
                            {% render_field form.data_renovacao class+="form-control" %}
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Observação</span>
                            </div>
                            {% render_field form.observacao class+="form-control" %}
                        </div>
                        <hr />
                        <div class="text-right">
                            <a href="{% url 'curso:lista_curso' %}" class="btn btn-outline-primary">Voltar</a>
                            <button type="submit" class="btn btn-primary">Atualiza</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

appprincipal/templates/curso/cadast_curso.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

{% load widget_tweaks %}

<!-- Bloco de conteúdo da nossa página -->

{% block conteudo %}



<div class="container mt-3">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Nome da Instituição</label>
            {% render_field form.nome_inst %}
        </div>
        <div class="form-group">
            <label>Nome do Curso</label>
            {% render_field form.nome_curso %}
        </div>
        <div class="form-group">
            <label>Grau Curso</label>
            {% render_field form.grau_curso %}
        </div>
        <div class="form-group">
            <label>Código e-MEC</label>
            {% render_field form.cod_emec %}
        </div>
        <div class="form-group">
            <label>Data Autorização</label>
            {% render_field form.data_autorizacao %}
        </div>
        <div class="form-group">
            <label>Data Reconhecimento</label>
            {% render_field form.data_reconhecimento %}
        </div>
        <div class="form-group">
            <label>Data Renovação</label>
            {% render_field form.data_renovacao %}
        </div>
        <div class="form-group">
            <label>Observacao</label>
            {% render_field form.observacao %}
        </div>

        <button type="submit">Cadastrar</button>

    </form>
</div>


{% endblock %}

appprincipal/templates/curso/cursoacesso.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}


<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}

<div class="container mt-5">
<h2><a href="#">Cursos</a></h2>
</br>
	<p class="mb-3">Funções </p>
<a href="{% url 'curso:curso_cadast' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Cadastrar Cursos</a></br></br>
<a href="{% url 'curso:lista_curso' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Lista Cursos Cadastrados</a>

{% endblock %}

appprincipal/templates/curso/cursos.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

<!-- Bloco de conteúdo da nossa página -->

{% block conteudo %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Cursos Ofertados:</h5>

            <p class="card-text">

            </p>

            <form method="post">
                            
<table class="table table-hover">
    <thead>
        <tr>
            <th>Tipo do Curso</th>
            <th>Grau do Curso</th>
            <th>Codigo e-MEC</th>
            <th>Nome da Instituição</th>
            <th></th>
        </tr>
    </thead>              
                   
    
        <tbody>  {% for cursos in cursos %} <tr>
                <td>{{ cursos.nome_curso }}</td>
                <td>{{ cursos.grau_curso }}</td>
                <td>{{ cursos.cod_emec }}</td> 
                <td>{{ cursos.nome_inst }}</td>
                <td><a href="{% url 'curso:update_curso' cursos.id %}" class="btn btn-primary" >Atualizar</a></td>
                <td><a href="{% url 'curso:deleta_curso' cursos.id %}" class="btn btn-danger" >Deletar</a></td>
            </tr> {% endfor %}
        </tbody>
    
               
            </form>
</table>
        </div>
    </div>
</div>
{% endblock %}

appprincipal/templates/curso/exclui_curso.html
<!-- Estendemos do template base  -->
{% extends "appprincipal/_layouts/base.html" %}

<!-- Bloco de conteúdo da nossa página -->

{% block conteudo %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Exclusão de Curso</h5>

            <p class="card-text">
                Você tem certeza que quer excluir o curso <b>{{ Curso.nome_curso }}</b>?
            </p>

            <form method="post">
                {% csrf_token %}

                <hr />
                <div class="text-right">
                    <a href="{% url 'curso:lista_curso' %}" class="btn btn-outline-danger">
                        Cancelar
                    </a>
                    <button class="btn btn-danger">Excluir</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}